$streams = {
	"JB FM 99,9" => "http://18903.live.streamtheworld.com/JBFMAAC1",
	"Atlântida FM 101,7" => "rtsp://wz3.dnip.com.br/sc_atla/sc_atla.stream",
	"Antena 1 SP" => "http://antena1.newradio.it/stream2",
    "Antena 1 103,7 RJ" => "http://www.antena1rio.com.br/player/?pl=vlc&c=Antena%201%20-%20103,7%20-%20Rio%20de%20Janeiro",
    "MPB FM (web)" => "rtmp://evp.mm.uol.com.br:1935/mpb_rj/_definst_/mpb_rj.sdp",
    "CBN RJ" => "http://media.sgr.globo.com/CBNRD/cbnrj.sdp/playlist.m3u8",
    "Bandnews FM RJ" => "http://evp.mm.uol.com.br/bnewsfm_rj/bnewsfm_rj.sdp/playlist.m3u8",
    "89 FM A Rádio Rock SP" => "http://streaming.shoutcast.com/89FMARADIOROCK",
    "Jovem Pan News SP" => "http://live.webradio.upx.net.br:8044/#Rádio Jovem Pan News (São Paulo) 900",
    "Soma FM - Left Coast 70s" => "https://somafm.com/seventies130.pls",
    "Soma FM - Seven Inch Soul (soul)" => "https://somafm.com/7soul130.pls",
    "Soma FM - Underground 80s" => "https://somafm.com/u80s130.pls",
    "Soma FM - Indie Pop Rocks!" => "https://somafm.com/indiepop130.pls",
    "Soma FM - Folk Forward" => "https://somafm.com/folkfwd130.pls",
    "Soma FM - BAGeL Radio (rock alternativo)" => "https://somafm.com/bagel130.pls",
    "Soma FM - Groove Salad (eletrônico)" => "https://somafm.com/groovesalad130.pls",
    "Soma FM - Sonic Universe (jazz)" => "https://somafm.com/sonicuniverse130.pls",
    "Soma FM - Beat Blender (calma)" => "https://somafm.com/beatblender130.pls",
    "Shoutcast - Jazz and Lounge station" => "http://yp.shoutcast.com/sbin/tunein-station.pls?id=99263886",
    "Shoutcast - Calm Radio" => "http://yp.shoutcast.com/sbin/tunein-station.pls?id=1219771",
    "Shoutcast - Beatles Radio" => "http://yp.shoutcast.com/sbin/tunein-station.pls?id=1091354",
    "Cope (Listenlive)" => "http://www.listenlive.eu/cadenacope.m3u",
    "Cope Madrid (Tunein)" => "http://net2.cope.stream.flumotion.com/cope/net2-low.mp3.m3u"
}
