require "pifi/version"
require "pifi/controllers/static_controller"
require "pifi/controllers/player_controller"
require "pifi/controllers/streams_controller"
require "pifi/controllers/config_controller"
